/*ESTRUCTURA DDL PARA EL TP DE LA POKEDEX*/ 
CREATE DATABASE pokedex;
USE pokedex;

CREATE TABLE pokemon(
        id INT AUTO_INCREMENT PRIMARY KEY,
        numero_identificador INT NOT NULL,
        imagen VARCHAR(255),
        nombre VARCHAR(100),
        tipo1 VARCHAR(50) NOT NULL,
        tipo2 VARCHAR(50),
        descripcion VARCHAR(700)
);

CREATE TABLE usuarios(
    id INT AUTO_INCREMENT PRIMARY KEY,
    usuario VARCHAR(30) NOT NULL UNIQUE,
    contrasenia VARCHAR(25) NOT NULL,
    es_admin BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE pokemones_propios(
    id INT AUTO_INCREMENT PRIMARY KEY,
    id_usuario INT NOT NULL,
    numero_identificador INT NOT NULL,
    imagen VARCHAR(255),
    nombre VARCHAR(100),
    tipo1 VARCHAR(50) NOT NULL,
    tipo2 VARCHAR(50),
    descripcion VARCHAR(700),
    FOREIGN KEY (id_usuario) REFERENCES usuario(id)
);

INSERT INTO pokemon (numero_identificador, imagen, nombre, tipo1, tipo2, descripcion) VALUES
(1, 'imagenes/pokemones/1.png', 'Bulbasaur', 'Planta', 'Veneno','Bulbasaur nace con una semilla en el lomo que crece con el tiempo.\nEs conocido por su naturaleza tranquila y su fuerte vínculo con la vegetación.'),
(2, 'imagenes/pokemones/2.png', 'Ivysaur', 'Planta', 'Veneno','Ivysaur desarrolla una flor en su lomo que florece con la luz del sol.\nSe vuelve más fuerte cuando pasa tiempo bajo el sol, absorbiendo energía.'),
(3, 'imagenes/pokemones/3.png', 'Venusaur', 'Planta', 'Veneno','La flor de Venusaur libera un aroma que calma a los Pokémon cercanos.\nEste Pokémon alcanza su máximo poder bajo la luz solar intensa.'),
(4, 'imagenes/pokemones/4.png', 'Charmander', 'Fuego', NULL,'Charmander tiene una llama en su cola que indica su estado de salud.\nEs juguetón, pero puede ser feroz si se le provoca.'),
(5, 'imagenes/pokemones/5.png', 'Charmeleon', 'Fuego', NULL,'Charmeleon es más agresivo y valiente que su preevolución.\nSu llama arde con más fuerza cuando está emocionado o enojado.'),
(6, 'imagenes/pokemones/6.png', 'Charizard', 'Fuego', 'Volador','Charizard vuela a grandes alturas y es capaz de lanzar llamaradas.\nEs un Pokémon feroz y muy territorial cuando se siente amenazado.'),
(7, 'imagenes/pokemones/7.png', 'Squirtle', 'Agua', NULL,'Squirtle es conocido por su caparazón duro y su habilidad para disparar agua.\nEste Pokémon es muy leal a su entrenador y siempre protege a los débiles.'),
(8, 'imagenes/pokemones/8.png', 'Wartortle', 'Agua', NULL,'Wartortle es más rápido y agresivo que Squirtle.\nSu cola se vuelve más prominente con el tiempo, siendo un signo de su crecimiento.'),
(9, 'imagenes/pokemones/9.png', 'Blastoise', 'Agua', NULL,'Blastoise tiene cañones de agua en su espalda que pueden disparar agua a presión.\nEs conocido por su resistencia y su enorme poder en combate.'),
(10, 'imagenes/pokemones/10.png', 'Caterpie', 'Bicho', NULL,'Caterpie es un Pokémon de tipo bicho que se alimenta de hojas.\nA pesar de ser pequeño, es muy ágil y su capullo tiene propiedades protectoras.'),
(11, 'imagenes/pokemones/11.png', 'Metapod', 'Bicho', NULL,'Metapod es la forma en la que Caterpie se transforma antes de evolucionar.\nEste Pokémon es extremadamente vulnerable debido a su caparazón.'),
(12, 'imagenes/pokemones/12.png', 'Butterfree', 'Bicho', 'Volador','Butterfree tiene alas grandes y brillantes que utiliza para volar a grandes alturas.\nEs conocido por su habilidad para liberar polen venenoso en combate.'),
(13, 'imagenes/pokemones/13.png', 'Weedle', 'Bicho', 'Veneno','Weedle tiene un aguijón venenoso en su cola que utiliza para defenderse.\nEs un Pokémon tímido pero puede ser muy peligroso si se siente amenazado.'),
(14, 'imagenes/pokemones/14.png', 'Kakuna', 'Bicho', 'Veneno','Kakuna es una forma en la que Weedle pasa por su metamorfosis.\nEs un Pokémon inmóvil, pero tiene una gran fuerza escondida en su interior.'),
(15, 'imagenes/pokemones/15.png', 'Beedrill', 'Bicho', 'Veneno','Beedrill es rápido y muy agresivo, con dos aguijones venenosos en sus manos.\nEste Pokémon protege su colmena con gran ferocidad.'),
(16, 'imagenes/pokemones/16.png', 'Pidgey', 'Normal', 'Volador','Pidgey es un Pokémon muy común en áreas rurales y bosques.\nEs conocido por su habilidad para volar largas distancias y regresar a su hogar.'),
(17, 'imagenes/pokemones/17.png', 'Pidgeotto', 'Normal', 'Volador','Pidgeotto es más grande y más fuerte que su preevolución.\nEste Pokémon se convierte en una amenaza para los pequeños Pokémon de la zona.'),
(18, 'imagenes/pokemones/18.png', 'Pidgeot', 'Normal', 'Volador','Pidgeot es el líder de los Pidgey y Pidgeotto.\nEs un Pokémon majestuoso y muy rápido, capaz de volar a velocidades impresionantes.'),
(19, 'imagenes/pokemones/19.png', 'Rattata', 'Normal', NULL,'Rattata es pequeño pero rápido, conocido por su tenacidad en combate.\nSe alimenta de frutas y es común en zonas urbanas.'),
(20, 'imagenes/pokemones/20.png', 'Raticate', 'Normal', NULL,'Raticate es más grande y más fuerte que su preevolución.\nEs un Pokémon muy competitivo y se considera una plaga en algunas regiones.'),
(21, 'imagenes/pokemones/21.png', 'Spearow', 'Normal', 'Volador','Spearow es conocido por su agresividad y su habilidad para atacar en bandada.\nEste Pokémon es extremadamente territorial.'),
(22, 'imagenes/pokemones/22.png', 'Fearow', 'Normal', 'Volador','Fearow tiene un cuello largo que le permite ver a grandes distancias.\nEste Pokémon es más grande y más fuerte que su preevolución.'),
(23, 'imagenes/pokemones/23.png', 'Ekans', 'Veneno', NULL,'Ekans es un Pokémon serpiente que puede enrollarse y atacar con gran rapidez.\nSu veneno es altamente tóxico para otros Pokémon.'),
(24, 'imagenes/pokemones/24.png', 'Arbok', 'Veneno', NULL,'Arbok tiene un cuerpo largo y puede intimidar con su capucho expandido.\nEste Pokémon es extremadamente peligroso cuando se enfurece.'),
(25, 'imagenes/pokemones/25.png', 'Pikachu', 'Eléctrico', NULL,'Pikachu es conocido por su gran energía y su habilidad para generar electricidad.\nEs el compañero de Ash Ketchum en sus aventuras.'),
(26, 'imagenes/pokemones/26.png', 'Raichu', 'Eléctrico', NULL,'Raichu es más rápido y más poderoso que su preevolución.\nEste Pokémon puede generar electricidad de forma más eficiente.'),
(27, 'imagenes/pokemones/27.png', 'Sandshrew', 'Tierra', NULL,'Sandshrew tiene una piel dura que lo protege de los ataques físicos.\nEste Pokémon excava rápidamente para escapar de sus enemigos.'),
(28, 'imagenes/pokemones/28.png', 'Sandslash', 'Tierra', NULL,'Sandslash es mucho más grande y fuerte que su preevolución.\nSus garras le permiten excavar a grandes profundidades.'),
(29, 'imagenes/pokemones/29.png', 'Nidoran', 'Veneno', NULL,'Nidoran es un Pokémon pequeño pero valiente, conocido por sus habilidades defensivas.\nSu aguijón es venenoso y lo usa para defenderse.'),
(30, 'imagenes/pokemones/30.png', 'Nidorina', 'Veneno', NULL,'Nidorina es más grande que Nidoran y tiene una personalidad más protectora.\nAunque no puede evolucionar sin una Piedra Lunar, es muy fuerte.'),
(31, 'imagenes/pokemones/31.png', 'Nidoqueen', 'Veneno', 'Tierra','Nidoqueen es un Pokémon de gran tamaño y fuerza física.\nEs conocido por su capacidad para proteger su territorio con fiereza.'),
(32, 'imagenes/pokemones/32.png', 'Nidoran', 'Veneno', NULL,'Nidoran es un Pokémon pequeño, con una naturaleza curiosa y exploradora.\nSu aguijón en la espalda es peligroso para los Pokémon de su tamaño.'),
(33, 'imagenes/pokemones/33.png', 'Nidorino', 'Veneno', NULL,'Nidorino es un Pokémon más agresivo que su preevolución.\nEs muy territorial y se puede poner muy agresivo cuando se siente amenazado.'),
(34, 'imagenes/pokemones/34.png', 'Nidoking', 'Veneno', 'Tierra','Nidoking es extremadamente fuerte y feroz.\nSu cuerno es su arma principal, y puede atacar con una gran fuerza física y elemental.'),
(35, 'imagenes/pokemones/35.png', 'Clefairy', 'Hada', NULL,'Clefairy es un Pokémon tímido que prefiere estar en la oscuridad de la noche.\nEs muy protector de sus amigos y tiene poderes místicos.'),
(36, 'imagenes/pokemones/36.png', 'Clefable', 'Hada', NULL,'Clefable es conocido por su capacidad para usar poderes psíquicos y mágicos.\nEste Pokémon tiene una gran resistencia y es muy difícil de derrotar.'),
(37, 'imagenes/pokemones/37.png', 'Vulpix', 'Fuego', NULL,'Vulpix es un Pokémon pequeño y adorable con seis colas.\nSu fuego es cálido y puede controlar la temperatura que genera.'),
(38, 'imagenes/pokemones/38.png', 'Ninetales', 'Fuego', NULL,'Ninetales es un Pokémon sabio y misterioso, con ocho colas que se dice son portadoras de poderes mágicos.\nPuede conjurar fuego con facilidad.'),
(39, 'imagenes/pokemones/39.png', 'Jigglypuff', 'Normal', 'Hada','Jigglypuff tiene una voz suave que puede hacer que los demás se duerman al instante.\nEste Pokémon es muy cariñoso y le gusta cantar.'),
(40, 'imagenes/pokemones/40.png', 'Wigglytuff', 'Normal', 'Hada','Wigglytuff es mucho más grande y fuerte que su preevolución.\nEs conocido por su capacidad para llenar de sueño a todos los que lo escuchan cantar.'),
(41, 'imagenes/pokemones/41.png', 'Zubat', 'Veneno', 'Volador','Zubat es un Pokémon que se encuentra comúnmente en cavernas y minas.\nEste Pokémon se guía por la ecolocalización y tiene una gran velocidad.'),
(42, 'imagenes/pokemones/42.png', 'Golbat', 'Veneno', 'Volador','Golbat es mucho más agresivo que su preevolución y usa su boca grande para atacar.\nEs un Pokémon que puede ser difícil de detener en combate.'),
(43, 'imagenes/pokemones/43.png', 'Oddish', 'Planta', 'Veneno','Oddish tiene una forma similar a una flor, y se alimenta de la luz solar.\nEs conocido por su capacidad para liberar esporas venenosas en su defensa.'),
(44, 'imagenes/pokemones/44.png', 'Gloom', 'Planta', 'Veneno','Gloom tiene un olor desagradable que puede debilitar a sus oponentes.\nEs un Pokémon que se encuentra en zonas húmedas y sombreadas.'),
(45, 'imagenes/pokemones/45.png', 'Vileplume', 'Planta', 'Veneno','Vileplume tiene una gran flor en su cabeza que libera un polen venenoso.\nEste Pokémon es conocido por su habilidad para controlar plantas.'),
(46, 'imagenes/pokemones/46.png', 'Paras', 'Bicho', 'Planta','Paras es un Pokémon que vive en simbiosis con los hongos que crecen en su espalda.\nEstos hongos tienen propiedades que pueden ser utilizadas en medicina.'),
(47, 'imagenes/pokemones/47.png', 'Parasect', 'Bicho', 'Planta','Parasect es más grande que su preevolución, y sus hongos son mucho más peligrosos.\nEs un Pokémon que puede liberar esporas venenosas.'),
(48, 'imagenes/pokemones/48.png', 'Venonat', 'Bicho', 'Veneno','Venonat tiene ojos grandes que le permiten ver en la oscuridad.\nEs un Pokémon que se esconde entre la vegetación para cazar.'),
(49, 'imagenes/pokemones/49.png', 'Venomoth', 'Bicho', 'Veneno','Venomoth tiene alas que brillan a la luz, y usa su veneno para defenderse de los ataques.\nEste Pokémon es muy sigiloso y difícil de detectar en el aire.'),
(50, 'imagenes/pokemones/50.png', 'Diglett', 'Tierra', NULL,'Diglett vive bajo tierra y es muy difícil de ver.\nEste Pokémon excava rápidamente y puede moverse a gran velocidad por debajo de la tierra.'),
(51, 'imagenes/pokemones/51.png', 'Dugtrio', 'Tierra', NULL,'Dugtrio es una versión más potente y rápida de Diglett.\nEste Pokémon tiene tres cabezas y excava a gran velocidad.'),
(52, 'imagenes/pokemones/52.png', 'Meowth', 'Normal', NULL,'Meowth es un Pokémon muy astuto, conocido por su habilidad para robar objetos.\nEste Pokémon es famoso por su carácter travieso y su amor por el dinero.'),
(53, 'imagenes/pokemones/53.png', 'Persian', 'Normal', NULL,'Persian es elegante y muy rápido.\nEste Pokémon tiene una personalidad altiva y se le considera un símbolo de estatus.'),
(54, 'imagenes/pokemones/54.png', 'Psyduck', 'Agua', NULL,'Psyduck es un Pokémon que sufre dolores de cabeza constantes debido a sus poderes psíquicos.\nCuando estos dolores alcanzan su punto máximo, puede liberar grandes cantidades de energía.'),
(55, 'imagenes/pokemones/55.png', 'Golduck', 'Agua', NULL,'Golduck es más rápido y ágil que Psyduck, y puede controlar su energía psíquica de manera efectiva.\nEs un experto nadador y puede atacar de manera certera.'),
(56, 'imagenes/pokemones/56.png', 'Mankey', 'Lucha', NULL,'Mankey es muy impulsivo y tiende a atacar sin pensarlo.\nEste Pokémon es rápido y feroz, y tiene una gran resistencia en combate.'),
(57, 'imagenes/pokemones/57.png', 'Primeape', 'Lucha', NULL,'Primeape es aún más agresivo que su preevolución.\nEste Pokémon puede ser extremadamente peligroso si se le provoca.'),
(58, 'imagenes/pokemones/58.png', 'Growlithe', 'Fuego', NULL,'Growlithe es un Pokémon leal, conocido por su naturaleza amigable.\nEs un excelente compañero y su lealtad a su entrenador es inquebrantable.'),
(59, 'imagenes/pokemones/59.png', 'Arcanine', 'Fuego', NULL,'Arcanine es un Pokémon majestuoso y extremadamente rápido.\nEste Pokémon es conocido por su fuerza y su gran corazón.'),
(60, 'imagenes/pokemones/60.png', 'Poliwag', 'Agua', NULL,'Poliwag es un Pokémon anfibio que vive en ambientes acuáticos.\nSu cuerpo es pequeño, pero se adapta perfectamente al agua.'),
(61, 'imagenes/pokemones/61.png', 'Poliwhirl', 'Agua', NULL,'Poliwhirl es la etapa intermedia de Poliwag, con una cola más fuerte y un mayor control del agua.\nEste Pokémon es conocido por su habilidad para nadar rápidamente.'),
(62, 'imagenes/pokemones/62.png', 'Politoed', 'Agua', NULL,'Politoed tiene una gran capacidad de vocalización.\nEste Pokémon es conocido por su canto, que puede encantar a otros Pokémon y seres humanos.'),
(63, 'imagenes/pokemones/63.png', 'Abra', 'Psíquico', NULL,'Abra es un Pokémon que usa sus habilidades psíquicas para teletransportarse.\nEste Pokémon es muy sensible a los ruidos y prefiere estar solo en lugares tranquilos.'),
(64, 'imagenes/pokemones/64.png', 'Kadabra', 'Psíquico', NULL,'Kadabra es un Pokémon que se convierte más fuerte conforme desarrolla sus poderes psíquicos.\nEste Pokémon puede realizar increíbles telequinesis.'),
(65, 'imagenes/pokemones/65.png', 'Alakazam', 'Psíquico', NULL,'Alakazam es uno de los Pokémon más inteligentes.\nCon su enorme poder psíquico, puede manipular objetos a su voluntad.'),
(66, 'imagenes/pokemones/66.png', 'Machop', 'Lucha', NULL,'Machop es un Pokémon con una gran fuerza física.\nEste Pokémon entrena constantemente para convertirse en un luchador más fuerte.'),
(67, 'imagenes/pokemones/67.png', 'Machoke', 'Lucha', NULL,'Machoke es un luchador experimentado y tiene una increíble fuerza física.\nEste Pokémon es conocido por su capacidad para resistir grandes cantidades de daño.'),
(68, 'imagenes/pokemones/68.png', 'Machamp', 'Lucha', NULL,'Machamp es un Pokémon de combate extremadamente fuerte y resistente.\nEste Pokémon puede levantar objetos pesados con facilidad y tiene un aguante inigualable.'),
(69, 'imagenes/pokemones/69.png', 'Bellsprout', 'Planta', 'Veneno','Bellsprout es un Pokémon que puede utilizar su tallo como un látigo para atacar.\nEste Pokémon es conocido por su habilidad para moverse rápidamente por la vegetación.'),
(70, 'imagenes/pokemones/70.png', 'Weepinbell', 'Planta', 'Veneno','Weepinbell es la etapa intermedia de Bellsprout, y tiene un mayor control sobre su tallo.\nEste Pokémon es capaz de liberar ácido de su boca.'),
(71, 'imagenes/pokemones/71.png', 'Victreebel', 'Planta', 'Veneno','Victreebel tiene una gran boca que usa para atrapar a sus presas.\nEste Pokémon es extremadamente venenoso y usa su ácido para defenderse.'),
(72, 'imagenes/pokemones/72.png', 'Tentacool', 'Agua', 'Veneno','Tentacool es un Pokémon acuático con tentáculos venenosos que utiliza para defenderse.\nEs conocido por ser un nadador excepcionalmente rápido.'),
(73, 'imagenes/pokemones/73.png', 'Tentacruel', 'Agua', 'Veneno','Tentacruel tiene tentáculos largos que pueden paralizar a sus oponentes.\nEste Pokémon es muy resistente y puede atacar a larga distancia.'),
(74, 'imagenes/pokemones/74.png', 'Geodude', 'Roca', 'Tierra','Geodude es un Pokémon rocoso con una gran resistencia a los golpes.\nEste Pokémon es muy territorial y usa su fuerza para defender su territorio.'),
(75, 'imagenes/pokemones/75.png', 'Graveler', 'Roca', 'Tierra','Graveler es más fuerte que Geodude y puede levantar rocas grandes con facilidad.\nEste Pokémon es conocido por su increíble fuerza física.'),
(76, 'imagenes/pokemones/76.png', 'Golem', 'Roca', 'Tierra','Golem es un Pokémon extremadamente fuerte que puede rodar a gran velocidad.\nEste Pokémon es conocido por su durabilidad y su poder destructivo.'),
(77, 'imagenes/pokemones/77.png', 'Ponyta', 'Fuego', NULL,'Ponyta es un Pokémon con una melena de fuego que se enciende cuando corre.\nEs muy ágil y puede alcanzar altas velocidades en poco tiempo.'),
(78, 'imagenes/pokemones/78.png', 'Rapidash', 'Fuego', NULL,'Rapidash es conocido por su gran velocidad y por su imponente melena de fuego.\nEste Pokémon es un competidor formidable en cualquier carrera.'),
(79, 'imagenes/pokemones/79.png', 'Slowpoke', 'Agua', 'Psíquico','Slowpoke es un Pokémon que parece estar siempre distraído, pero su poder psíquico es inmenso.\nEste Pokémon se mueve lentamente, pero sus ataques son letales cuando se concentra.'),
(80, 'imagenes/pokemones/80.png', 'Slowbro', 'Agua', 'Psíquico','Slowbro está unido a un Shellder que se ha adherido a su cola.\nEste Pokémon puede usar su poder psíquico para controlar su entorno a gran distancia.'),
(81, 'imagenes/pokemones/81.png', 'Magnemite', 'Eléctrico', 'Acero','Magnemite es un Pokémon de forma redonda que genera campos magnéticos.\nEste Pokémon puede moverse gracias a su capacidad para atraer objetos metálicos.'),
(82, 'imagenes/pokemones/82.png', 'Magneton', 'Eléctrico', 'Acero','Magneton es una versión más potente de Magnemite, formada por tres de ellos unidos.\nEste Pokémon tiene un gran control sobre los campos magnéticos y puede usarlo como ataque.'),
(83, 'imagenes/pokemones/83.png', 'Farfetch\'d', 'Normal', 'Volador','Farfetch\'d es un Pokémon que lleva una cebollita en su pico como símbolo de su habilidad para el combate.\nEste Pokémon es muy territorial y le gusta desafiar a otros Pokémon.'),
(84, 'imagenes/pokemones/84.png', 'Doduo', 'Normal', 'Volador','Doduo es un Pokémon de dos cabezas que se mueve rápidamente.\nEs conocido por su velocidad y por ser capaz de correr a grandes distancias en poco tiempo.'),
(85, 'imagenes/pokemones/85.png', 'Dodrio', 'Normal', 'Volador','Dodrio es una versión más rápida y feroz de Doduo.\nEste Pokémon tiene tres cabezas, y cada una tiene una personalidad distinta, lo que lo hace impredecible en combate.'),
(86, 'imagenes/pokemones/86.png', 'Seel', 'Agua', NULL, 'Seel es un Pokémon de aspecto acuático con un cuerpo esférico.\nEste Pokémon se mueve rápidamente por el agua y es conocido por su habilidad para nadar.'),
(87, 'imagenes/pokemones/87.png', 'Dewgong', 'Agua', 'Hielo', 'Dewgong es la evolución de Seel y tiene un cuerpo elegante.\nEste Pokémon puede nadar a gran velocidad y usar sus colas para atacar a sus oponentes.'),
(88, 'imagenes/pokemones/88.png', 'Grimer', 'Veneno', NULL, 'Grimer es un Pokémon de tipo veneno con un cuerpo viscoso.\nEste Pokémon vive en áreas contaminadas y es capaz de generar sustancias tóxicas.'),
(89, 'imagenes/pokemones/89.png', 'Muk', 'Veneno', NULL, 'Muk es la evolución de Grimer y tiene un cuerpo más grande y pegajoso.\nEste Pokémon se mueve dejando una estela de sustancias tóxicas y es muy resistente.'),
(90, 'imagenes/pokemones/90.png', 'Shellder', 'Agua', NULL, 'Shellder es un pequeño Pokémon con una concha dura.\nEste Pokémon se protege en su concha y usa su rápida lengua para atrapar a sus presas.'),
(91, 'imagenes/pokemones/91.png', 'Cloyster', 'Agua', 'Hielo', 'Cloyster es la evolución de Shellder y tiene una concha extremadamente fuerte.\nEste Pokémon puede disparar agua a alta presión y usar su concha como una defensa impenetrable.'),
(92, 'imagenes/pokemones/92.png', 'Gastly', 'Fantasma', 'Veneno', 'Gastly es un Pokémon de tipo fantasma que flota en el aire.\nEste Pokémon puede atacar con energía espiritual y es capaz de hacerse invisible para escapar de los peligros.'),
(93, 'imagenes/pokemones/93.png', 'Haunter', 'Fantasma', 'Veneno', 'Haunter es la evolución de Gastly y tiene una apariencia más aterradora.\nEste Pokémon puede poseer a otros y se alimenta de la energía vital de sus víctimas.'),
(94, 'imagenes/pokemones/94.png', 'Gengar', 'Fantasma', 'Veneno', 'Gengar es la evolución final de Gastly y tiene una forma sólida.\nEste Pokémon se oculta en las sombras y es capaz de causar pesadillas a sus oponentes.'),
(95, 'imagenes/pokemones/95.png', 'Onix', 'Roca', 'Tierra', 'Onix es un Pokémon gigante formado por piedras.\nEste Pokémon es muy resistente y usa su cuerpo largo para atacar a sus enemigos con grandes golpes.'),
(96, 'imagenes/pokemones/96.png', 'Drowzee', 'Psíquico', NULL, 'Drowzee es un Pokémon que usa su poder psíquico para dormir a sus oponentes.\nEste Pokémon se alimenta de los sueños de los humanos y puede controlar sus mentes.'),
(97, 'imagenes/pokemones/97.png', 'Hypno', 'Psíquico', NULL, 'Hypno es la evolución de Drowzee y tiene un poder psíquico mucho mayor.\nEste Pokémon usa su reloj de bolsillo para hipnotizar a sus oponentes y controlarlos a su voluntad.'),
(98, 'imagenes/pokemones/98.png', 'Krabby', 'Agua', NULL, 'Krabby es un pequeño Pokémon cangrejo que vive en la playa.\nEste Pokémon es conocido por sus poderosas pinzas y su capacidad para escapar rápidamente del peligro.'),
(99, 'imagenes/pokemones/99.png', 'Kingler', 'Agua', NULL, 'Kingler es la evolución de Krabby y tiene unas pinzas mucho más grandes.\nEste Pokémon es muy fuerte y puede usar sus pinzas para romper objetos duros con facilidad.'),
(100, 'imagenes/pokemones/100.png', 'Voltorb', 'Eléctrico', NULL, 'Voltorb es un Pokémon de tipo eléctrico que se asemeja a una bola con una cara.\nEste Pokémon puede generar electricidad y explotar en un destello eléctrico.'),
(101, 'imagenes/pokemones/101.png', 'Electrode', 'Eléctrico', NULL, 'Electrode es la evolución de Voltorb y tiene una forma más redonda.\nEste Pokémon puede almacenar energía eléctrica y liberar descargas a gran escala.'),
(102, 'imagenes/pokemones/102.png', 'Exeggcute', 'Planta', 'Psíquico', 'Exeggcute es un grupo de seis huevos que están conectados entre sí.\nEste Pokémon es capaz de liberar energía psíquica y usarla para protegerse.'),
(103, 'imagenes/pokemones/103.png', 'Exeggutor', 'Planta', 'Psíquico', 'Exeggutor es la evolución de Exeggcute y tiene una gran altura.\nEste Pokémon puede manipular las plantas a su alrededor y tiene una gran sabiduría.'),
(104, 'imagenes/pokemones/104.png', 'Cubone', 'Tierra', NULL, 'Cubone es un pequeño Pokémon que siempre lleva un cráneo sobre su cabeza.\nEste Pokémon es muy solitario y usa su hueso para defenderse de los enemigos.'),
(105, 'imagenes/pokemones/105.png', 'Marowak', 'Tierra', NULL, 'Marowak es la evolución de Cubone y tiene un cuerpo más fuerte.\nEste Pokémon usa su hueso para atacar a sus oponentes y proteger a su familia.'),
(106, 'imagenes/pokemones/106.png', 'Hitmonlee', 'Lucha', NULL, 'Hitmonlee es un Pokémon experto en el uso de patadas.\nEste Pokémon tiene una gran flexibilidad y puede ejecutar patadas muy poderosas desde cualquier ángulo.'),
(107, 'imagenes/pokemones/107.png', 'Hitmonchan', 'Lucha', NULL, 'Hitmonchan es un Pokémon experto en el uso de puños.\nEste Pokémon puede lanzar puñetazos rápidos y poderosos, como si fueran ráfagas de viento.'),
(108, 'imagenes/pokemones/108.png', 'Lickitung', 'Normal', NULL, 'Lickitung es un Pokémon que tiene una lengua extremadamente larga.\nEste Pokémon utiliza su lengua para atrapar objetos y defenderse de sus enemigos.'),
(109, 'imagenes/pokemones/109.png', 'Koffing', 'Veneno', NULL, 'Koffing es un Pokémon que emite gases venenosos desde su cuerpo.\nEste Pokémon utiliza sus gases para atrapar a sus presas y debilitar a sus enemigos.'),
(110, 'imagenes/pokemones/110.png', 'Weezing', 'Veneno', NULL, 'Weezing es la evolución de Koffing y tiene un cuerpo mucho más grande.\nEste Pokémon es capaz de liberar gases venenosos de manera más poderosa y puede moverse flotando a través del aire.'),
(111, 'imagenes/pokemones/111.png', 'Rhyhorn', 'Roca', 'Tierra', 'Rhyhorn es un Pokémon con un cuerpo de roca y una gran fuerza.\nEste Pokémon es muy resistente y utiliza su gran cuerno para atacar a sus enemigos.'),
(112, 'imagenes/pokemones/112.png', 'Rhydon', 'Roca', 'Tierra', 'Rhydon es la evolución de Rhyhorn y es mucho más grande y fuerte.\nEste Pokémon puede perforar a través de rocas con su cuerno y es muy temido por su poder.'),
(113, 'imagenes/pokemones/113.png', 'Chansey', 'Normal', NULL, 'Chansey es un Pokémon muy amable y protector.\nEste Pokémon se encuentra frecuentemente en hospitales y ayuda a curar a otros con su huevo especial.'),
(114, 'imagenes/pokemones/114.png', 'Tangela', 'Planta', NULL, 'Tangela es un Pokémon cubierto por lianas de plantas.\nEste Pokémon puede usar sus lianas para defenderse de los ataques y para atrapar a sus presas.'),
(115, 'imagenes/pokemones/115.png', 'Kangaskhan', 'Normal', NULL, 'Kangaskhan es un Pokémon que lleva a su cría en una bolsa en su abdomen.\nEste Pokémon es muy protector con su cría y puede luchar con gran fuerza.'),
(116, 'imagenes/pokemones/116.png', 'Horsea', 'Agua', NULL, 'Horsea es un pequeño Pokémon acuático que se asemeja a un caballito de mar.\nEste Pokémon puede disparar chorros de agua a gran presión para defenderse.'),
(117, 'imagenes/pokemones/117.png', 'Seadra', 'Agua', NULL, 'Seadra es la evolución de Horsea y tiene una apariencia más serpentina.\nEste Pokémon puede moverse rápidamente en el agua y tiene una gran destreza en combate.'),
(118, 'imagenes/pokemones/118.png', 'Goldeen', 'Agua', NULL, 'Goldeen es un pequeño pez dorado que nada rápidamente.\nEste Pokémon puede saltar fuera del agua y usar sus aletas como si fueran cuchillas.'),
(119, 'imagenes/pokemones/119.png', 'Seaking', 'Agua', NULL, 'Seaking es la evolución de Goldeen y tiene una gran elegancia.\nEste Pokémon es conocido por sus grandes aletas y su habilidad para nadar a gran velocidad.'),
(120, 'imagenes/pokemones/120.png', 'Staryu', 'Agua', NULL, 'Staryu es un Pokémon con forma de estrella de mar.\nEste Pokémon puede regenerar sus partes dañadas y tiene una joya en el centro de su cuerpo.'),
(121, 'imagenes/pokemones/121.png', 'Starmie', 'Agua', 'Psíquico', 'Starmie es la evolución de Staryu y es más poderosa.\nEste Pokémon puede usar su joya central para liberar poder psíquico y controlar las corrientes de agua.'),
(122, 'imagenes/pokemones/122.png', 'Mr. Mime', 'Psíquico', 'Hada', 'Mr. Mime es un Pokémon que utiliza su poder psíquico para crear barreras invisibles.\nEste Pokémon puede manipular objetos a su alrededor y tiene una gran agilidad.'),
(123, 'imagenes/pokemones/123.png', 'Scyther', 'Bicho', 'Volador', 'Scyther es un Pokémon que tiene un cuerpo delgado y afilado.\nEste Pokémon es muy rápido y usa sus alas y garras para atacar con gran precisión.'),
(124, 'imagenes/pokemones/124.png', 'Jynx', 'Hielo', 'Psíquico', 'Jynx es un Pokémon con una figura humanoide que puede congelar a sus oponentes.\nEste Pokémon utiliza su poder psíquico para manipular el frío y la temperatura.'),
(125, 'imagenes/pokemones/125.png', 'Electabuzz', 'Eléctrico', NULL, 'Electabuzz es un Pokémon eléctrico con una gran cantidad de energía.\nEste Pokémon puede generar electricidad en su cuerpo y lanzar rayos a sus oponentes.'),
(126, 'imagenes/pokemones/126.png', 'Magmar', 'Fuego', NULL, 'Magmar es un Pokémon con un cuerpo envuelto en llamas.\nEste Pokémon puede generar fuego intenso en su cuerpo y usa este poder para defenderse.'),
(127, 'imagenes/pokemones/127.png', 'Pinsir', 'Bicho', NULL, 'Pinsir es un Pokémon con grandes mandíbulas.\nEste Pokémon usa sus poderosas mandíbulas para atrapar y destruir a sus oponentes.'),
(128, 'imagenes/pokemones/128.png', 'Tauros', 'Normal', NULL, 'Tauros es un Pokémon con una gran fuerza física.\nEste Pokémon es muy territorial y puede correr a gran velocidad para defender su espacio.'),
(129, 'imagenes/pokemones/129.png', 'Magikarp', 'Agua', NULL, 'Magikarp es un Pokémon que se considera débil y poco útil.\nEste Pokémon es conocido por su habilidad de saltar a grandes alturas, pero su poder real se revela solo en su evolución.'),
(130, 'imagenes/pokemones/130.png', 'Gyarados', 'Agua', 'Volador', 'Gyarados es la evolución de Magikarp y es un Pokémon muy feroz.\nEste Pokémon puede generar tormentas con su fuerza y tiene una apariencia de dragón aterradora.'),
(131, 'imagenes/pokemones/131.png', 'Lapras', 'Agua', 'Hielo', 'Lapras es un Pokémon de gran tamaño que se parece a un plesiosaurio.\nEste Pokémon es conocido por su gentileza y su habilidad para nadar rápidamente.'),
(132, 'imagenes/pokemones/132.png', 'Ditto', 'Normal', NULL, 'Ditto es un Pokémon con la capacidad de transformarse en cualquier otro Pokémon.\nEste Pokémon es muy raro y puede imitar las habilidades y ataques de otros Pokémon.'),
(133, 'imagenes/pokemones/133.png', 'Eevee', 'Normal', NULL, 'Eevee es un Pokémon que tiene múltiples evoluciones posibles.\nEste Pokémon es muy flexible y se adapta a diferentes entornos y condiciones.'),
(134, 'imagenes/pokemones/134.png', 'Vaporeon', 'Agua', NULL, 'Vaporeon es una de las evoluciones de Eevee y tiene el poder del agua.\nEste Pokémon puede manipular el agua y transformarse en vapor o líquido.'),
(135, 'imagenes/pokemones/135.png', 'Jolteon', 'Eléctrico', NULL, 'Jolteon es una de las evoluciones de Eevee y tiene el poder del rayo.\nEste Pokémon es extremadamente rápido y puede generar electricidad a gran velocidad.'),
(136, 'imagenes/pokemones/136.png', 'Flareon', 'Fuego', NULL, 'Flareon es una de las evoluciones de Eevee y tiene el poder del fuego.\nEste Pokémon puede generar llamas intensas y usa su calor para atacar a sus enemigos.'),
(137, 'imagenes/pokemones/137.png', 'Porygon', 'Normal', NULL, 'Porygon es un Pokémon artificial creado a partir de datos computacionales.\nEste Pokémon puede cambiar su forma y adaptarse a diferentes entornos virtuales.'),
(138, 'imagenes/pokemones/138.png', 'Omanyte', 'Roca', 'Agua', 'Omanyte es un Pokémon que vive en el agua y tiene una concha en espiral.\nEste Pokémon es muy antiguo y pertenece a una especie extinta que ha sido revivida.'),
(139, 'imagenes/pokemones/139.png', 'Omastar', 'Roca', 'Agua', 'Omastar es la evolución de Omanyte y tiene una forma más elegante.\nEste Pokémon es muy hábil para nadar y puede utilizar sus tentáculos para atacar.'),
(140, 'imagenes/pokemones/140.png', 'Kabuto', 'Roca', 'Agua', 'Kabuto es un Pokémon prehistórico que tiene una gran concha protectora.\nEste Pokémon es conocido por su agilidad y su resistencia bajo el agua.'),
(141, 'imagenes/pokemones/141.png', 'Kabutops', 'Roca', 'Agua', 'Kabutops es la evolución de Kabuto y tiene una gran habilidad de combate.\nEste Pokémon usa sus afiladas patas para cortar a sus enemigos con gran precisión.'),
(142, 'imagenes/pokemones/142.png', 'Aerodactyl', 'Roca', 'Volador', 'Aerodactyl es un Pokémon prehistórico que tiene una gran capacidad de vuelo.\nEste Pokémon es conocido por su velocidad en el aire y su aguda visión.'),
(143, 'imagenes/pokemones/143.png', 'Snorlax', 'Normal', NULL, 'Snorlax es un Pokémon extremadamente grande y pesado.\nEste Pokémon pasa la mayor parte de su tiempo durmiendo y es conocido por su increíble fuerza cuando se despierta.'),
(144, 'imagenes/pokemones/144.png', 'Articuno', 'Hielo', 'Volador', 'Articuno es uno de los tres Pokémon legendarios.\nEste Pokémon tiene el poder de controlar el hielo y las tormentas de nieve.'),
(145, 'imagenes/pokemones/145.png', 'Zapdos', 'Eléctrico', 'Volador', 'Zapdos es otro de los tres Pokémon legendarios.\nEste Pokémon puede generar rayos y tiene el poder de controlar el clima eléctrico.'),
(146, 'imagenes/pokemones/146.png', 'Moltres', 'Fuego', 'Volador', 'Moltres es el último de los tres Pokémon legendarios.\nEste Pokémon puede crear llamas intensas y es conocido por su aspecto de ave fénix.'),
(147, 'imagenes/pokemones/147.png', 'Dratini', 'Dragón', NULL, 'Dratini es un pequeño Pokémon dragón que tiene una forma serpentina.\nEste Pokémon crece hasta convertirse en un Dragón formidable cuando evoluciona.'),
(148, 'imagenes/pokemones/148.png', 'Dragonair', 'Dragón', NULL, 'Dragonair es la evolución de Dratini y tiene una apariencia más majestuosa.\nEste Pokémon tiene un control total sobre las corrientes de aire y puede volar.'),
(149, 'imagenes/pokemones/149.png', 'Dragonite', 'Dragón', 'Volador', 'Dragonite es la evolución final de Dratini.\nEste Pokémon es muy poderoso y puede viajar a gran velocidad tanto en el aire como en el agua.'),
(150, 'imagenes/pokemones/150.png', 'Mewtwo', 'Psíquico', NULL, 'Mewtwo es un Pokémon creado artificialmente por científicos.\nEste Pokémon tiene una gran fuerza psíquica y puede controlar la mente de otros Pokémon.');

INSERT INTO usuario(usuario, contrasenia) VALUES 
('usuario1', '1234'),
('usuario2', '4321');